spring.application.name=micropeliculas
server.port=8080

# Conexión BD Oracle
spring.datasource.url=jdbc:oracle:thin:@dsy2206_tp?TNS_ADMIN=C:/Users/La Diva/Downloads/Wallet_N2BF0YPY58FJ8KAM
spring.datasource.username=ADMIN
spring.datasource.password=ClaveEmpresa1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG
